background{
	monitor =
	path = /home/vita_bite/Pictures/wallpapers/joy_xxx.jpg
	blur_passes = 2
	blur_size = 2
	brightness = 0.5
}
input-field {
	monitor =
	size = 300, 50
	outline_thickness = 3
	rounding = 15
	dots_size = 0.2
	dots_spacing = 0.35
	font_color = rgba(0, 0, 0, 1)
	outer_color = rgba(250, 189, 47, 1)
	inner_color = rgba(80, 73, 69, 1)
	check_color = rgba(0, 0, 0, 1)
	fail_color = rgba(255, 255, 255, 1)
	placeholder_text = WAITING...
	fail_text = ERROR!
	position = 0, -100
	fade_on_empty = false
	dots_center = true
	halign = center
	valign = center
}
label {
	text = cmd[update:1000] echo "$(date +"%A, %B %d")"
	color = rgba(250, 189, 47, 1)
	font_size = 22
	font_family = JetBrains Mono
	position = 0, 500
}
label {
	text = $TIME
	color = rgba(250, 189, 47, 1)
	font_size = 22
	font_family = JetBrains Mono
	position = 0, 450
}
label {
	text = $USER
	color = rgba(184, 187, 38, 1)
	font_size = 40
	font_family = JetBrains Mono
	position = 0, 600
}
label {
	text = $ATTEMPTS
	color = rgba(255, 255, 255, 1)
	font_size = 22
	font_family = JetBrains Mono
	position = 0, -400
}
label {
	text = $FAIL
	color = rgba(255, 255, 255, 1)
	font_size = 22
	font_family = JetBrains Mono
	position = 0, -350
}
